# Generated by Django 2.2.15 on 2021-08-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210803_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Additional field', 'verbose_name_plural': 'Additional fields'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=2, verbose_name='Bio'),
            preserve_default=False,
        ),
    ]
